"""add otp table

Revision ID: 08671fd4f41c
Revises: 1b6f53dd7004
Create Date: 2026-03-18 16:46:41.729185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08671fd4f41c'
down_revision: Union[str, Sequence[str], None] = '1b6f53dd7004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp', sa.Column('otp', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otp', 'otp')
    # ### end Alembic commands ###
