"""add otp table

Revision ID: c90decd37113
Revises: 08671fd4f41c
Create Date: 2026-03-18 17:01:23.254171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c90decd37113'
down_revision: Union[str, Sequence[str], None] = '08671fd4f41c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp', sa.Column('hashed_otp', sa.Integer(), nullable=False))
    op.drop_column('otp', 'otp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp', sa.Column('otp', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('otp', 'hashed_otp')
    # ### end Alembic commands ###
